version: '3.8'

services:
  # Main Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///booking_system.db
      - JWT_SECRET_KEY=your-secret-key-here
      - NOTIFICATION_SERVICE_URL=http://notification-service:5002
      - CRM_SERVICE_URL=http://crm-service:5001
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - notification-service
      - crm-service
    networks:
      - booking-network

  # CRM Service
  crm-service:
    build:
      context: ./crm_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///crm_system.db
      - BACKEND_SERVICE_URL=http://backend:5000
    volumes:
      - ./crm_service:/app
      - crm_data:/app/data
    networks:
      - booking-network

  # Notification Service
  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///notifications.db
      - BACKEND_SERVICE_URL=http://backend:5000
      - CRM_SERVICE_URL=http://crm-service:5001
    volumes:
      - ./notification_service:/app
      - notification_data:/app/data
    networks:
      - booking-network

volumes:
  backend_data:
  crm_data:
  notification_data:

networks:
  booking-network:
    driver: bridge
